<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '-- Select Parent Department --' => '',
    'Actual Budget' => '',
    'Address' => '',
    'Birthday' => '',
    'Child' => '',
    'Color Identifier' => '',
    'Companies' => '',
    'Company' => '',
    'Company ID' => '',
    'Contact ID' => '',
    'Contacts' => '',
    'Create' => '',
    'Created At' => '',
    'Created By' => '',
    'Delete' => '',
    'Demo Url' => '',
    'Department' => '',
    'Department ID' => '',
    'Departments' => '',
    'Description' => '',
    'Email' => '',
    'End Date' => '',
    'End Time' => '',
    'First Name' => '',
    'ID' => '',
    'Im' => '',
    'Job' => '',
    'Last Name' => '',
    'Notes' => '',
    'Parent' => '',
    'Percent Complete' => '',
    'Phone' => '',
    'Priority' => '',
    'Project ID' => '',
    'Project Management' => '',
    'Projects' => '',
    'Reset' => '',
    'Search' => '',
    'Start Date' => '',
    'Start Time' => '',
    'Status' => '',
    'Target Budget' => '',
    'Task ID' => '',
    'Tasks' => '',
    'Title' => '',
    'Type' => '',
    'Update' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Url' => '',
    'Website' => '',
];
